<?php

declare(strict_types=1);

namespace Hereldar\DoctrineMapping\Enums;

/**
 * The mode of automatically generate IDs.
 */
enum Generated: string
{
    /**
     * The column value is never generated by the database.
     */
    case Never = 'NEVER';

    /**
     * The column value is generated by the database on INSERT, but
     * not on UPDATE.
     */
    case Insert = 'INSERT';

    /**
     * The column value is generated by the database on both INSERT
     * and UDPATE statements.
     */
    case Always = 'ALWAYS';

    /**
     * @return int<0, 2>
     *
     * @internal
     */
    public function internalValue(): int
    {
        return match ($this) {
            self::Never => 0,
            self::Insert => 1,
            self::Always => 2,
        };
    }
}
