<?php

declare(strict_types=1);

namespace Hereldar\DoctrineMapping\Enums;

/**
 * The mode of automatically generate IDs.
 *
 * @property-read value-of<Generated::VALUES> $value
 *
 * TODO: convert to a backed enum when PHP 8.1 is the minimum version
 */
final class Generated
{
    /** @use BackedEnum<string> */
    use BackedEnum;

    /**
     * The column value is never generated by the database.
     */
    public const Never = 'NEVER';

    /**
     * The column value is generated by the database on INSERT, but
     * not on UPDATE.
     */
    public const Insert = 'INSERT';

    /**
     * The column value is generated by the database on both INSERT
     * and UDPATE statements.
     */
    public const Always = 'ALWAYS';

    private const VALUES = [
        self::Never,
        self::Insert,
        self::Always,
    ];

    /**
     * @return int<0, 2>
     *
     * @internal
     */
    public function internalValue(): int
    {
        return match ($this->value) {
            self::Never => 0,
            self::Insert => 1,
            self::Always => 2,
        };
    }
}
